CREATE USER 'shop'@'localhost' IDENTIFIED BY '비밀번호';

GRANT USAGE ON *.* TO 'shop'@'localhost';

GRANT EXECUTE, SELECT, SHOW VIEW, ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE TEMPORARY TABLES, CREATE VIEW, DELETE, DROP, EVENT, INDEX, INSERT, REFERENCES, TRIGGER, UPDATE, LOCK TABLES  ON `shop`.* TO 'shop'@'localhost' WITH GRANT OPTION;

FLUSH PRIVILEGES; -- 권한을 즉시 부여하겠다.